# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Bootstrap-agency"
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
# baseurl: ""
baseurl: "/agency_ext" # the subpath of your site, e.g. /blog
# url: http://admien33.github.io # the base hostname & protocol for your site
url: # the base hostname & protocol for your site
path_image_baseurl: images
path_image_originals: images/_originals

# twitter_username: lacasebiocoutras
# github_username:  lacasebiocoutras
# lang: fr
# words_per_minute: 150


# Jekyll configuration
# permalink: /:categories/:title.html
permalink: /:path.html
# permalink: /:year/:month/:title.html
# permalink: pretty
# excerpt_separator: <!--fin-excerpt-->



# Configuration settings you cannot change from https://help.github.com/articles/configuring-jekyll/

# Produce an index for related posts:
# lsi: false
# Disable custom plugins, and ignore symbolic links:
#safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#    noscript: false




# Build settings
markdown: kramdown

# sass:
#   sass_dir: _assets/stylesheets
#   style: compressed
# _layouts/compress.html
compress_html:
  clippings: all
  endings: all
  comments: all # ["<!--", "-->"]



keep_files: [images] #conserver dans fichier destination, _site par défaut
# include: ["_pages"]

exclude:
  - gulp
  - node_modules
  - .asset-cache
  - .editorconfig
  - .gitignore
  - .jshintrc
  - .ruby-version
  - Gemfile*
  - README.md
  - autoprefixer.yml
  - gulpfile.js
  - package.json
  - _site/
  - .code-highlighter-cache
  - Rakefile.rb
  - vendor
  - .travis.yml
  - deploy.sh
  - deploy_init.sh

# Plugins
whitelist: []
plugins:
  - jekyll-assets # generate locally !
  - jekyll-sitemap

# Plugin: jekyll-assets

assets:
  sources:
    - _assets/js
    - _assets/stylesheets
    # - _assets/images
    # - _assets/fonts
    # - _assets/scss_liquid
    # - _assets/css_lib
    - _assets/font-awesome
  compress:
    css: true
    js: true
  cache: false
  digest: true
  #fait planter carousel, optim css si active, a analyser, todo
  features:
    liquid: true





collections:    
  agency:
    output: false
    permalink: /:path.html
    title: agency  
  detailed-contents:
    output: false
    permalink: /:path.html
    title: detailed-contents  
  pages:
    output: true
    permalink: /:path.html
    title: pages


collections_ext:
  # ! dependence : site.baseurl
  url_extension_section: /index.html
  url_extension_item: .html
  path_extension_section: /index.md

# Defaults
defaults:  
  # agency
  - scope:
      path: _agency
      type: agency
    values:
      layout:
  # detailed-contents
  - scope:
      path: _detailed-contents
      type: detailed-contents
    values:
      layout:
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout:


# Plugin: jekyll-picture-tag

picture:
  source: "images/_originals"
  output: "images"
  markup: "picture"
  presets:
    default:
      ppi: [1]
      source_720:
        media: "(min-width: 1200px)"
        width: "720"
      source_670:
        media: "(min-width: 768px)"
        width: "670"
      source_540:
        media: "(min-width: 600px)"
        width: "540"
      source_default:
        width: "320"
    portfolio-thumbnail:
      attr:
        class: "img-responsive img-centered"
        itemprop: "image"      
      source_default:
        width: "400"   
    portfolio-header-image:
      attr:
        class: "img-responsive img-centered"
        itemprop: "image"      
      source_default:
        width: "600"
    about-timeline-miniature:
      attr:
        class: "img-responsive img-circle"
        itemprop: "image"      
      source_default:
        width: "200"
        height: "200" 
    clients-miniature:
      attr:
        class: "img-responsive img-centered"
        itemprop: "image"      
      source_default:
        width: "200"
        height: "50"  
    team-miniature:
      attr:
        class: "img-responsive img-circle"
        itemprop: "image"      
      source_default:
        width: "225"
        height: "225"
    services-miniature:
      attr:
        class: "img-responsive img-centered img-circle"
        itemprop: "image"      
      source_default:
        width: "112"
        height: "112"  
   
